#!/usr/bin/env python3
"""Generate the C++ fixture header from the shared normalizer contract.

    python etl/gen_cpp_fixtures.py

Emits ``tests/normalize_cases.inc`` from ``etl/tests/normalize_cases.json`` so
the C++ test asserts the same table as the Python test. Generating a header
rather than reading the JSON at runtime keeps the C++ side free of a JSON parser
and makes a stale fixture a compile-time change instead of a silent skip.

Run this whenever normalize_cases.json changes; the C++ test fails loudly if the
two drift, which is the entire point.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ETL_DIR = Path(__file__).resolve().parent
REPO_ROOT = ETL_DIR.parent
SOURCE = ETL_DIR / "tests" / "normalize_cases.json"
TARGET = REPO_ROOT / "tests" / "normalize_cases.inc"


def cpp_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def main() -> int:
    cases = json.loads(SOURCE.read_text(encoding="utf-8"))["cases"]

    lines = [
        "// Generated by etl/gen_cpp_fixtures.py -- do not edit.",
        f"// Source: etl/tests/normalize_cases.json ({len(cases)} cases)",
        "",
        "// clang-format off",
        "static const NormalizeCase kNormalizeCases[] = {",
    ]

    for case in cases:
        keys = ", ".join(cpp_string(k) for k in case["keys"])
        lines.append("    {")
        lines.append(f"        /* raw       */ {cpp_string(case['raw'])},")
        lines.append(f"        /* function  */ {cpp_string(case['function'])},")
        lines.append(f"        /* module    */ {cpp_string(case['module'] or '')},")
        lines.append(
            f"        /* ordinal   */ {case['ordinal'] if case['ordinal'] is not None else -1},"
        )
        lines.append(
            f"        /* is_apiset */ {'true' if case['is_apiset'] else 'false'},"
        )
        lines.append(f"        /* keys      */ {{{keys}}},")
        lines.append(f"        /* canonical */ {cpp_string(case['canonical'])},")
        lines.append("    },")

    lines.append("};")
    lines.append("// clang-format on")
    lines.append("")

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {TARGET} ({len(cases)} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
